<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><IsPackable>true</IsPackable></PropertyGroup><ItemGroup><ProjectReference Include="../BqAtlas.Core/BqAtlas.Core.csproj" /><PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" /><PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" /><FrameworkReference Include="Microsoft.AspNetCore.App" /></ItemGroup><PropertyGroup><PackageReadmeFile>README.md</PackageReadmeFile></PropertyGroup><ItemGroup><None Include="README.md" Pack="true" PackagePath="/" /><None Include="../../../docs/SOURCE-NOTICE.md" Pack="true" PackagePath="/SOURCE-NOTICE.md" /></ItemGroup></Project>
