<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><IsPackable>false</IsPackable></PropertyGroup><ItemGroup><ProjectReference Include="../Crm.Contracts/Crm.Contracts.csproj" /><ProjectReference Include="../../../../../backend/src/BqAtlas.EntityFrameworkCore/BqAtlas.EntityFrameworkCore.csproj" /><ProjectReference Include="../../../../../backend/src/BqAtlas.AspNetCore/BqAtlas.AspNetCore.csproj" /><ProjectReference Include="../../../../../backend/src/BqAtlas.OData/BqAtlas.OData.csproj" /><FrameworkReference Include="Microsoft.AspNetCore.App" /></ItemGroup></Project>
