<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><PackageType>Template</PackageType><PackageId>BqAtlas.Templates</PackageId><IncludeBuildOutput>false</IncludeBuildOutput><NoDefaultExcludes>true</NoDefaultExcludes><IncludeContentInPack>true</IncludeContentInPack><NoWarn>$(NoWarn);NU5128</NoWarn><EnableDefaultCompileItems>false</EnableDefaultCompileItems><IsPackable>true</IsPackable></PropertyGroup><ItemGroup><Content Include="content/**/*" Pack="true" PackagePath="content" /></ItemGroup><PropertyGroup><PackageReadmeFile>README.md</PackageReadmeFile></PropertyGroup><ItemGroup><None Include="README.md" Pack="true" PackagePath="/" /><None Include="../../../docs/SOURCE-NOTICE.md" Pack="true" PackagePath="/SOURCE-NOTICE.md" /></ItemGroup></Project>
