<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><IsPackable>false</IsPackable><GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles><AssemblyName>BqAtlas.Sample.Migrations.PostgreSql</AssemblyName></PropertyGroup><ItemGroup><ProjectReference Include="../../Modules/Engagement/Engagement.csproj"/><ProjectReference Include="../../Modules/Sales/Sales.csproj" />
<ProjectReference Include="../../../../../backend/src/BqAtlas.Identity/BqAtlas.Identity.csproj" />
<ProjectReference Include="../../Modules/Crm/Crm.csproj" />
<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
<PackageReference Include="Microsoft.EntityFrameworkCore.Design"><PrivateAssets>all</PrivateAssets></PackageReference>
</ItemGroup></Project>
